name: Unzip Uploaded Files into Root


on:
  push:
  workflow_dispatch:

jobs:
  unzip-and-commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # This is important to allow pushes!

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Unzip all zip files into root
      run: |
        for f in *.zip; do
          [ -e "$f" ] || continue
          unzip -o "$f" -d .
          rm "$f"
        done

    - name: Commit and push unzipped content
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add .
        git diff --cached --quiet || git commit -m "Auto-unzipped into root"
        git push
      env:
        GIT_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # GitHub automatically creates this token—used below

    - name: Set remote to use token
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git push
